
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage,font



OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"/home/pi/projetos/tela1/assets/frame0")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


Employees = {
  '0013087914': {
    "name" : "Júlia Z. Schwartz",
    "position" : "Dev Backend",
     "last": "Today"
  },
  '0003866073': {
    "name" : "Maria da Silva",
    "position" : "Data Engineer",
     "last": "Today"
  },
  '0002710499': {
    "name" : "João Da Silva",
    "position" : "DevOps",
    "last": "Yesterday"
  }
}
for tent in range(10):

        try:
            ser = serial.Serial('/dev/ttyUSB'+tent, 9600, timeout=1)

            ser.reset_input_buffer()

            print("porta"+tent+"encontrada")

        except:

            print('porta não encontrada')

if ser.in_waiting > 0:
      line = ser.readline().decode('utf-8').rstrip();
      Employees[line]
      canvas.itemconfig("number", text=Employees[line])
      canvas.itemconfig("name", text=Employees[line].name)
      canvas.itemconfig("position", text=Employees[line].position)
      canvas.itemconfig("last", text=Employees[line].last)



window = Tk()

window.geometry("716x490")
window.configure(bg = "#FFFFFF")

Inter = font.Font(family="Inter Regular", size= 13)

canvas = Canvas(
    window,
    bg = "#FFFFFF",
    height = 490,
    width = 716,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
canvas.create_rectangle(
    272.0,
    0.0,
    716.0,
    490.0,
    fill="#F5F5F5",
    outline="")

canvas.create_rectangle(
    0.0,
    0.0,
    272.0,
    490.0,
    fill="#000000",
    outline="")

canvas.create_text(
    298.0,
    29.0,
    anchor="nw",
    text="Access Control Application",
    fill="#515156",
    font= ("Inter ExtraBold", 23 * -1)
)

canvas.create_text(
    300.0,
    62.0,
    anchor="nw",
    text="Quarta, 01 Maio, 2024, 13:09 ",
    fill="#A2A2A2",
    font=("Inter ExtraLight", 14 * -1)
)

image_image_1 = PhotoImage(
    file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(
    67.0,
    285.0,
    image=image_image_1
)

canvas.create_text(
    91.0,
    347.0,
    anchor="nw",
    text="Settings",
    fill="#FFFFFF",
    font=("Inter", 15* -1)
)

image_image_2 = PhotoImage(
    file=relative_to_assets("image_2.png"))
image_2 = canvas.create_image(
    112.0,
    226.0,
    image=image_image_2
)

canvas.create_text(
    89.0,
    273.0,
    anchor="nw",
    text="Past Records",
    fill="#FFFFFF",
    font=("Inter", 15*-1)
)

canvas.create_rectangle(
    55.0,
    325.0,
    232.0,
    326.0,
    fill="#FFFFFF",
    outline="")

image_image_3 = PhotoImage(
    file=relative_to_assets("image_3.png"))
image_3 = canvas.create_image(
    129.0,
    61.0,
    image=image_image_3
)

image_image_4 = PhotoImage(
    file=relative_to_assets("image_4.png"))
image_4 = canvas.create_image(
    122.9100341796875,
    166.0,
    image=image_image_4
)

image_image_5 = PhotoImage(
    file=relative_to_assets("image_5.png"))
image_5 = canvas.create_image(
    68.0,
    360.0,
    image=image_image_5
)

image_image_6 = PhotoImage(
    file=relative_to_assets("image_6.png"))
image_6 = canvas.create_image(
    491.0,
    238.0,
    image=image_image_6
)

number = canvas.create_text(
    358.0,
    156.0,
    anchor="nw",
    text="90020034530",
    fill="#646474",
    font=("Inter Medium", 18 * -1)
)

name = canvas.create_text(
    356.0,
    199.0,
    anchor="nw",
    text="Júlia Z. Schwartz",
    fill="#01150C",
    font=("Inter ExtraBold", 23 * -1)
)

canvas.create_text(
    360.0,
    299.0,
    anchor="nw",
    text="Last time checked: ",
    fill="#515156",
    font=("Inter ExtraLight", 14 * -1)
)

canvas.create_text(
    569.0,
    159.0,
    anchor="nw",
    text="Employee",
    fill="#646474",
    font=("Inter Regular", 9 * -1)
)

last = canvas.create_text(
    569.0,
    300.0,
    anchor="nw",
    text="Today",
    fill="#006710",
    font=("Inter Light", 14 * -1)
)

image_image_7 = PhotoImage(
    file=relative_to_assets("image_7.png"))
image_7 = canvas.create_image(
    408.0,
    258.0,
    image=image_image_7
)

position= canvas.create_text(
    369.0,
    250.0,
    anchor="nw",
    text="Dev Backend",
    fill="#212123",
    font=("Inter Light", 11 * -1)
)
window.resizable(True, True),
window.attributes("-fullscreen", True)
window.mainloop()
